
name: Daily Entity Image Refresh

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:     # Allows manual trigger from GitHub UI
    inputs:
      enable_health_check:
        description: 'Enable image health checking'
        required: false
        default: 'true'
        type: choice
        options:
        - 'true'
        - 'false'
      batch_size:
        description: 'Batch size for processing'
        required: false
        default: '10'
        type: string
      dry_run:
        description: 'Run in dry-run mode (no actual changes)'
        required: false
        default: 'false'
        type: choice
        options:
        - 'true'
        - 'false'

jobs:
  refresh-images:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Edge Function
        run: |
          curl -X POST https://uyjtgybbktgapspodajy.supabase.co/functions/v1/daily-refresh-entity-images \
            -H "Authorization: Bearer ${{ secrets.REFRESH_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "batchSize": ${{ github.event.inputs.batch_size || 10 }}, 
              "dryRun": ${{ github.event.inputs.dry_run == "true" }},
              "enableHealthCheck": ${{ github.event.inputs.enable_health_check != "false" }},
              "maxRetries": 2
            }'
